// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXB7Vg1CKL_UWhCj2USYFBVkRD0f0SXT4',
    appId: '1:337798518748:web:98c9731a9687cb5cc12119',
    messagingSenderId: '337798518748',
    projectId: 'apb-gmaps',
    authDomain: 'apb-gmaps.firebaseapp.com',
    storageBucket: 'apb-gmaps.firebasestorage.app',
    measurementId: 'G-F2689L4NE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrY6OzOoRAUOiX8fTbSkpUm8KaXydAq6A',
    appId: '1:337798518748:android:7fb82ae4bc87f12ac12119',
    messagingSenderId: '337798518748',
    projectId: 'apb-gmaps',
    storageBucket: 'apb-gmaps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaiPmq-K4PzDh0A6sNy2j3G_zWyC07OWk',
    appId: '1:337798518748:ios:43c30bf12c289edec12119',
    messagingSenderId: '337798518748',
    projectId: 'apb-gmaps',
    storageBucket: 'apb-gmaps.firebasestorage.app',
    iosBundleId: 'com.example.telkomMapsFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaiPmq-K4PzDh0A6sNy2j3G_zWyC07OWk',
    appId: '1:337798518748:ios:43c30bf12c289edec12119',
    messagingSenderId: '337798518748',
    projectId: 'apb-gmaps',
    storageBucket: 'apb-gmaps.firebasestorage.app',
    iosBundleId: 'com.example.telkomMapsFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXB7Vg1CKL_UWhCj2USYFBVkRD0f0SXT4',
    appId: '1:337798518748:web:359fce5cc67e37f8c12119',
    messagingSenderId: '337798518748',
    projectId: 'apb-gmaps',
    authDomain: 'apb-gmaps.firebaseapp.com',
    storageBucket: 'apb-gmaps.firebasestorage.app',
    measurementId: 'G-0D15H2JLYX',
  );

}